name: Run Arukereso.py and save urls.txt

on:
  schedule:
    - cron: "36 14 * * *"  # minden nap 15:30 magyar idő (14:30 UTC)
  workflow_dispatch:        # manuálisan is indítható

jobs:
  run-arukereso:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Arukereso.py futtatása
        run: python Arukereso.py

      - name: urls.txt commitolása
        run: |
          if [ -f urls.txt ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add urls.txt
            git commit -m "Automatikus frissítés: $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "urls.txt nem jött létre, nincs mit commitolni."
          fi
