name: Run Arukereso scraper

on:
  schedule:
    - cron: "30 14 * * *"  # minden nap 15:30 magyar idő (14:30 UTC)
  workflow_dispatch:        # manuálisan is indítható

jobs:
  run-arukereso:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python telepítése
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
